### ISSUE TITLE
Shenandoah builds with "latest" label

### ISSUE THREAD

**Issue by shipilev** [2m/java-openjdk-shenandoah-pkgbuild#4]
Hey, I have noticed you are using Shenandoah from builds.shipilev.net, and our daily build rotation routine is probably quite problematic for PKGBUILD. I have recently changed the format for build name again, but fear not, there is now the stable symlink with "latest" label that has build number stripped. Maybe you want to update scripts to always point to that URL and avoid the mess with discovery. 

See for example:
 https://builds.shipilev.net/openjdk-shenandoah-jdk8/openjdk-shenandoah-jdk8-latest-x86_64-release.tar.xz

**Comment by 2m** [comment]
Thanks for the heads-up. However I am deprecating this package in favour of [jabba](https://aur.archlinux.org/packages/jabba/).
